apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: mariadb
type: Opaque
data:
  mariadb-root-password: cm9vdHBhc3N3b3Jk # base64 encoded value of 'rootpassword'
  mariadb-user: dXNlcg== # base64 encoded value of 'user'
  mariadb-password: cGFzc3dvcmQ= # base64 encoded value of 'password'
  mariadb-database: d29yZHByZXNz # base64 encoded value of 'wordpress'
